flaskr/models.py
from flaskr import db, login_manager
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    image_file = db.Column(db.String(20), nullable=False, default='default.jpg')
    password = db.Column(db.String(60), nullable=False)       

    def __repr__(self):
        return f"User('{self.username}', '{self.email}', '{self.image_file}')"

flaskr/users/forms.py
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import InputRequired, Length, Email, EqualTo, ValidationError
from flask_wtf import FlaskForm
from flaskr.models import User


class RegistrationForm(FlaskForm):
    username = StringField(
        'Username',
        validators=[InputRequired(), Length(min=4, max=20)]
    )
    email = StringField(
        'Email',
        validators=[InputRequired(), Email()]
    )
    password = PasswordField(
        'Password',
        validators=[InputRequired()]
    )
    confirm_password = PasswordField(
        'Confirm Password',
        validators=[InputRequired(), EqualTo('password')]
    )
    submit = SubmitField('Sign up')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError('That username is taken. Please choose a different name')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('That email is taken. Please choose a different email address')


class LoginForm(FlaskForm):
    email = StringField(
        'Email',
        validators=[InputRequired(), Email()]
    )
    password = PasswordField(
        'Password',
        validators=[InputRequired()]
    )
    remember = BooleanField('Remember Me')
    submit = SubmitField('Log In')

flaskr/__init__.py
import os

from flask import Flask
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from flask_sqlalchemy import SQLAlchemy
from flaskr.development_config import DevelopmentConfig

"""Create the database object"""
db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()


"""Creating an application factory"""
def create_app(test_config=None):
    """Create the app. The __name__ built-in variable sets the import_name.
    Instance_relative_config tells the app that the configuration files are relative to the instance folder."""
    app = Flask(__name__, instance_relative_config=True)

    """Configure the app. This sets default development configurations using the development_config file. 
    This can be committed to a repository"""
    app.config.from_object(DevelopmentConfig)

    """If no test_config is given, the default configurations will be overwritten by values from the config.py file
    located in the instance folder, only if this file exists. This can be used to set the real SECRET_KEY.
    If there is a test_config, that will be used to set and overwrite the default configuration."""
    if test_config is None:
        app.config.from_pyfile('config.py', silent=True)
    else:
        app.config.from_mapping(test_config)

    """Try to make an instance folder. If this folder already exists an OSError is raised.
    The instance folder is mandatory, since it will contain the database"""
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    """Create the database object"""
    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)

    from flaskr.users.routes import users
    from flaskr.main.routes import main

    app.register_blueprint(users)
    app.register_blueprint(main)

    return app

flaskr/main/routes.py
from flask import Blueprint, render_template, request

main = Blueprint('main', __name__)

@main.route('/')
def home():
    return render_template('home.html')

flaskr/users/routes.py
from flask import render_template, url_for, redirect, Blueprint, flash, request
from flask_login import login_user, current_user, logout_user
from flaskr import db, bcrypt
from flaskr.models import User
from flaskr.users.forms import RegistrationForm, LoginForm


users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Account created for {form.username.data}!', 'success')
        return redirect(url_for('users.login'))

    return render_template(
        'register.html', title='Register', form=form
    )
        

@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccesful. Please check email and password', 'danger')
    return render_template(
        'login.html', title='login', form=form
    )

    
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

flaskr/templates/home.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    <title>Flask Blog</title>
</head>

<body>
    {% if current_user.is_authenticated %}
        <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
    {% else %}
        <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
        <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
    {% endif %}
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
</body>
</html>

flaskr/templates/login.html
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend class="border-bottom mb-4">Log In</legend>
            <div class="mb-3">
                {{ form.email.label(class="form-label") }}

                {% if form.email.errors %}
                    {{ form.email(class="form-control is-invalid") }}
                    <div class=invalid-feedback>
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor%}
                    </div>
                {% else %}
                    {{ form.email(class="form-control") }}
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.password.label(class="form-label") }}

                {% if form.password.errors %}
                    {{ form.password(class="form-control is-invalid") }}
                    <div class=invalid-feedback>
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor%}
                    </div>
                {% else %}
                    {{ form.password(class="form-control") }}
                {% endif %}
            </div>
            <div class="form-check mb-3">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>
        <div class="mb-3">
            {{ form.submit(class="btn btn-outline-dark") }}
        </div>
    </form>
</div>
<div class="border-top pt-2">
    <small class="text-muted">
        Need An Account? <a class="ms-2" href="{{ url_for('users.register') }}">Sign Up Now!</a>
    </small>
</div>

flaskr/templates/register.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    <title>Flask Blog</title>
</head>

<body>
    
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset>
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="mb-3">
                    {{ form.username.label(class="form-label") }}
    
                    {% if form.username.errors %}
                        {{ form.username(class="form-control is-invalid") }}
                        <div class=invalid-feedback>
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor%}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control") }}
                    {% endif %}
                </div>
                <div class="mb-3">
                    {{ form.email.label(class="form-label") }}
    
                    {% if form.email.errors %}
                        {{ form.email(class="form-control is-invalid") }}
                        <div class=invalid-feedback>
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor%}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control") }}
                    {% endif %}
                </div>
                <div class="mb-3">
                    {{ form.password.label(class="form-label") }}
    
                    {% if form.password.errors %}
                        {{ form.password(class="form-control is-invalid") }}
                        <div class=invalid-feedback>
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor%}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control") }}
                    {% endif %}
                </div>
                <div class="mb-4">
                    {{ form.confirm_password.label(class="form-label") }}
    
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control is-invalid") }}
                        <div class=invalid-feedback>
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor%}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="mb-3">
                {{ form.submit(class="btn btn-outline-dark") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-2">
        <small class="text-muted">
            Already Have An Account? <a class="ms-2" href="{{ url_for('users.login') }}">Sign In</a>
        </small>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
</body>
</html>